swarm_api: https://api.gateway.ethswarm.org
web_url: https://final-ride.ethswarm.org
download_link: http://localhost:8080/index.html?download=%s
chunk_size_mb: 10
theme: dark
download_dir: C:\Users\Admin\Downloads
encrypt_default: true
